name: TEST Theorafile

on: 
  workflow_dispatch:
      
jobs:
  windows:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        variant: [Release]
    runs-on: ${{ matrix.os }}
    name: WASM ${{ matrix.variant }} on ${{ matrix.os }}
    steps:
      - name: Check out source
        uses: actions/checkout@v1
      - uses: mymindstorm/setup-emsdk@v7
      - name: Verify
        run: emcc -v    
      - name: Check working directory
        shell: bash
        run: |
          pwd
      - name: SDL2    
        shell: bash
        run: |
          git clone https://github.com/libsdl-org/SDL
          cd SDL
          mkdir emscripten-build
          cd emscripten-build
          emconfigure ../configure --host=wasm32-unknown-emscripten --disable-assembly --disable-threads --disable-cpuinfo CFLAGS="-O2 -Wno-warn-absolute-paths -Wdeclaration-after-statement -Werror=declaration-after-statement" --prefix="$PWD/emscripten-sdl2-installed"
          emmake make
          emmake make install
      - name: Theorafile
        shell: bash
        run: |         
          git clone https://github.com/FNA-XNA/Theorafile.git
          cd Theorafile
          mkdir emscripten-build
          cd emscripten-build
          emconfigure ../configure --host=wasm32-unknown-emscripten --disable-assembly --disable-threads --disable-cpuinfo CFLAGS="-O2 -Wno-warn-absolute-paths -Wdeclaration-after-statement -Werror=declaration-after-statement" --prefix="$PWD/emscripten-sdl2-installed"
          emmake make
          emmake make install
      - name: Copy Binaries (with new names)
        shell: bash
        run: |
          mkdir Binaries
          cp ./SDL/emscripten-build/emscripten-sdl2-installed/lib/libSDL2.a Binaries/SDL2.a
          cp ./Theorafile/emscripten-build//emscripten-sdl2-installed/lib/libtheorafile.a Binaries/libtheorafile.a
          7z a FNA-WASM.Binaries.zip Binaries/*
      - name: Archive ${{ matrix.variant }} WASM archive on ${{ matrix.os }}
        uses: actions/upload-artifact@master
        with:
          name: TEST Libraries for ${{ matrix.variant }} on ${{ matrix.os }}
          path: Test.zip  
