name: WASM Build (FNA)

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
      
jobs:
  windows:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        variant: [Release]
    runs-on: ${{ matrix.os }}
    name: UWP ${{ matrix.variant }} on ${{ matrix.os }}
    steps:
      - name: Check out source
        uses: actions/checkout@v1
      - uses: mymindstorm/setup-emsdk@v7
      - name: Verify
        run: emcc -v    
      - name: Create the fnalibs repo directory
        shell: bash
        run: |
          mkdir fnalibs
          cd fnalibs
      - name: SDL2    
        shell: bash
        run: |
          git clone https://github.com/libsdl-org/SDL
          cd SDL
          mkdir emscripten-build
          cd emscripten-build
          emconfigure ../configure --host=wasm32-unknown-emscripten --disable-assembly --disable-threads --disable-cpuinfo CFLAGS="-O2 -Wno-warn-absolute-paths -Wdeclaration-after-statement -Werror=declaration-after-statement" --prefix="$PWD/emscripten-sdl2-installed"
          emmake make
          emmake make install
          cd ../..
